createTopic:
  is_secure:   off

addTopic:
  is_secure:   off

addPost:
  is_secure:   off
  
deletePost:
  is_secure:   on
  credentials: [moderator]

deleteTopic:
  is_secure:   on
  credentials: [moderator]
    
toggleStick:
  is_secure:   on
  credentials: [moderator]

toggleLock:
  is_secure:   on
  credentials: [moderator]